plugins { id 'com.android.application' }

android {
    namespace 'com.example.leddeskclock'
    compileSdk 35
    defaultConfig {
        applicationId 'com.example.leddeskclock'
        minSdk 33
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
